# Generated by Django 5.0.7 on 2024-08-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="products/%Y/%m/%d"
            ),
        ),
    ]
