name: Django CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.37
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: pc_shop
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpassword
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate SECRET_KEY
        run: echo "SECRET_KEY=$(openssl rand -base64 32)" >> $GITHUB_ENV

      - name: Run migrations and tests
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_NAME: pc_shop
          DB_USER: testuser
          DB_PASSWORD: testpassword
        run: |
          python manage.py migrate
          python manage.py test