name: Django CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: 'root'  # Ustawia hasło dla użytkownika root
          MYSQL_DATABASE: 'pc_shop'  # Tworzy bazę danych
          MYSQL_USER: 'testuser'  # Tworzy dodatkowego użytkownika
          MYSQL_PASSWORD: 'testpassword'  # Hasło dla dodatkowego użytkownika
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        run: |
          python manage.py migrate

      - name: Run tests
        run: |
          python manage.py test
        env:
          DJANGO_SETTINGS_MODULE: myproject.settings
          DATABASE_URL: mysql://testuser:testpassword@localhost:3306/testdb
